wordpressImage:
  tag: 5.8.1-debian-10-r0
replicaCount: 3
service:
  type: NodePort
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - name: wordpress.example.com
      path: /
metrics:
  enabled: true